{
 "title": "BMS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Capacity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "targets": [
    { "expr": "bms_ah_percent", "legendFormat": "Capacity" }
   ]
  },
  {
   "title": "Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "targets": [
    { "expr": "bms_power" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "targets": [
    { "expr": "bms_temperature" }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "targets": [
    { "expr": "bms_voltage" }
   ]
  },
  {
   "title": "Cycles",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "targets": [
    { "expr": "bms_cycles" }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "bms_power", "legendFormat": "Power" }
   ]
  },
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "bms_ah_percent", "legendFormat": "Capacity" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "bms_temperature", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Cycles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bms_cycles", "legendFormat": "Cycles" }
   ]
  }
 ]
}